### PR TITLE
Add Exam Class

### LINKED ISSUE #5: Add Exam Class
Attributes - 
Exam type from defined types.
Date
Max Marks
Contribution
Course from course list
Obtained Marks
Proctored 

Method - 
Getter and Setter for all
Contribution to final score

### PR DESCRIPTION
**Pull request by tirth5828**
fix #5

### CODE REVIEW

**Comment by Im-Madhur-Gupta** [comment]
@tirth5828 LGTM, merging now.

**Comment by Im-Madhur-Gupta** [comment]
@tirth5828 bro I think we can add that String type Course parameter to this class, as we won't be running the code that error thing won't be a problem ig.

**Comment by tirth5828** [comment]
@Im-Madhur-Gupta Check now

**Comment by Im-Madhur-Gupta** [comment]
LGTM, merging now.

**Pull request merged**
