### PR TITLE
Added Semester Class

### PR DESCRIPTION
**Pull request by foram-patel-0201**
There are some errors which will be resolved when Achievements and Exam class will be created.

Solving issue #2

### CODE REVIEW

**Review by tirth5828 — CHANGES_REQUESTED** [review]
I think we can keep the year and semester variable private. 
Also, I think it will be good to make the add exam and add course method.
Everything else is fine and perfect.

**Comment by tirth5828** [comment]
Also, add Issue no. while putting PR , So that it will reflect in Issue as will that the PR is generated

**Comment by Im-Madhur-Gupta** [comment]
> I think we can keep the year and semester variable private. Also, I think it will be good to make the add exam and add course method. Everything else is fine and perfect.

Bro addExam() and addCourse() (basically to create a course list) will be added under a separate issue.

**Comment by tirth5828** [comment]
@Im-Madhur-Gupta Okay bro

**Review by tirth5828 — APPROVED** [review]
All good

**Comment by tirth5828** [comment]
Sorry for misunderstanding

**Pull request merged**
